# Generated by Django 2.2.6 on 2019-12-04 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 4, 22, 48, 6, 31911))),
                ('param1_name', models.CharField(max_length=255)),
                ('param1_value', models.FloatField()),
                ('param2_name', models.CharField(max_length=255)),
                ('param2_value', models.FloatField()),
                ('param3_name', models.CharField(max_length=255)),
                ('param3_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_with_extension', models.TextField(max_length=1000)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='FuzzyColorHistogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccomponent1', models.IntegerField()),
                ('ccomponent2', models.IntegerField()),
                ('ccomponent3', models.IntegerField()),
                ('value', models.FloatField(default=0)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.Extraction')),
            ],
        ),
        migrations.AddField(
            model_name='extraction',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.Image'),
        ),
        migrations.AddField(
            model_name='extraction',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.Method'),
        ),
        migrations.CreateModel(
            name='CumulativeColorHistogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccomponent1_min', models.IntegerField()),
                ('ccomponent1_max', models.IntegerField()),
                ('ccomponent2_min', models.IntegerField()),
                ('ccomponent2_max', models.IntegerField()),
                ('ccomponent3_min', models.IntegerField()),
                ('ccomponent3_max', models.IntegerField()),
                ('value', models.FloatField(default=0)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.Extraction')),
            ],
        ),
        migrations.CreateModel(
            name='ColorHistogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccomponent1_min', models.IntegerField()),
                ('ccomponent1_max', models.IntegerField()),
                ('ccomponent2_min', models.IntegerField()),
                ('ccomponent2_max', models.IntegerField()),
                ('ccomponent3_min', models.IntegerField()),
                ('ccomponent3_max', models.IntegerField()),
                ('value', models.FloatField(default=0)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.Extraction')),
            ],
        ),
        migrations.CreateModel(
            name='ColorCorrelogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.IntegerField()),
                ('ccomponent1_min', models.IntegerField()),
                ('ccomponent1_max', models.IntegerField()),
                ('ccomponent2_min', models.IntegerField()),
                ('ccomponent2_max', models.IntegerField()),
                ('ccomponent3_min', models.IntegerField()),
                ('ccomponent3_max', models.IntegerField()),
                ('value', models.FloatField(default=0)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.Extraction')),
            ],
        ),
        migrations.CreateModel(
            name='ColorCoherenceVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccomponent1', models.IntegerField()),
                ('ccomponent2', models.IntegerField()),
                ('ccomponent3', models.IntegerField()),
                ('alpha', models.IntegerField(default=0)),
                ('beta', models.IntegerField(default=0)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.Extraction')),
            ],
        ),
    ]
