# Generated by Django 2.2.6 on 2019-12-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_index', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.Method')),
            ],
        ),
        migrations.CreateModel(
            name='ColorHistogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.Image')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbir.ValueType')),
            ],
        ),
    ]
