# Generated by Django 2.2.6 on 2019-10-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorHistogram',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_0_0_0', models.IntegerField(default=0)),
                ('c_0_0_50', models.IntegerField(default=0)),
                ('c_0_0_100', models.IntegerField(default=0)),
                ('c_0_50_50', models.IntegerField(default=0)),
                ('c_45_50_50', models.IntegerField(default=0)),
                ('c_90_50_50', models.IntegerField(default=0)),
                ('c_135_50_50', models.IntegerField(default=0)),
                ('c_180_50_50', models.IntegerField(default=0)),
                ('c_225_50_50', models.IntegerField(default=0)),
                ('c_270_50_50', models.IntegerField(default=0)),
                ('c_315_50_50', models.IntegerField(default=0)),
                ('c_0_50_100', models.IntegerField(default=0)),
                ('c_45_50_100', models.IntegerField(default=0)),
                ('c_90_50_100', models.IntegerField(default=0)),
                ('c_135_50_100', models.IntegerField(default=0)),
                ('c_180_50_100', models.IntegerField(default=0)),
                ('c_225_50_100', models.IntegerField(default=0)),
                ('c_270_50_100', models.IntegerField(default=0)),
                ('c_315_50_100', models.IntegerField(default=0)),
                ('c_0_100_50', models.IntegerField(default=0)),
                ('c_45_100_50', models.IntegerField(default=0)),
                ('c_90_100_50', models.IntegerField(default=0)),
                ('c_135_100_50', models.IntegerField(default=0)),
                ('c_180_100_50', models.IntegerField(default=0)),
                ('c_225_100_50', models.IntegerField(default=0)),
                ('c_270_100_50', models.IntegerField(default=0)),
                ('c_315_100_50', models.IntegerField(default=0)),
                ('c_0_100_100', models.IntegerField(default=0)),
                ('c_45_100_100', models.IntegerField(default=0)),
                ('c_90_100_100', models.IntegerField(default=0)),
                ('c_135_100_100', models.IntegerField(default=0)),
                ('c_180_100_100', models.IntegerField(default=0)),
                ('c_225_100_100', models.IntegerField(default=0)),
                ('c_270_100_100', models.IntegerField(default=0)),
                ('c_315_100_100', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField(max_length=255)),
            ],
        ),
    ]
