# Generated by Django 2.2.6 on 2019-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField(max_length=255)),
            ],
        ),
    ]
